version: '3'
services:
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: dev
    env_file:
      - ./environments/.env.dev
    # volumes:
    #   - ./:/app
    command: npm run serve
